[env]
RUSTC_WRAPPER = ""
# Automatic virtualenv activation
_.python.venv = { path = "py_scnr/.venv", create = true }

[tools]
just = "latest"
python = "3"
uv = "latest"
"pipx:virtualenv" = "latest"
"cargo:maturin" = { version = "1.14", locked = true }
"pipx:maturin" = { version = "1.14" }
"pipx:maturin[patchelf]" = { version = "1.14" }
