name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Check
        run: just check

      - uses: EmbarkStudios/cargo-deny-action@v1

      - name: Install tooling
        run: just install_tooling

      - name: Test
        run: |
          just install_python_venv
          just test

      - name: Try install
        run: just install

      - name: Test examples
        run: just test_examples
